{
 "title": "Aircraft Dashboard Dump1090",
 "description": "Information about collected dump1090 data.",
 "tags": [
  "dump1090",
  "flightdata",
  "aircraft",
  "rtl-sdr"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Aircraft Record List",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (hex, flight, category, direction, squawk, airline) (dump1090prom_aircraft_flight_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aircraft Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(hex) (dump1090prom_aircraft_flight_info)",
     "legendFormat": "{{hex}} {{flight}}"
    }
   ]
  },
  {
   "title": "Aircraft Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(category, hex) (dump1090prom_aircraft_flight_info)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Aircraft Distance Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_distance_from_position_meters",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Emergency Squawk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_flight_info{squawk=\"7700\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dump1090prom_aircraft_flight_info{squawk=\"7601\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dump1090prom_aircraft_flight_info{squawk=\"7600\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dump1090prom_aircraft_flight_info{squawk=\"7500\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aircraft Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 19 },
   "targets": [
    { "expr": "dump1090prom_aircraft_count", "legendFormat": "Aircraft Count" }
   ]
  },
  {
   "title": "Squawks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "group by(hex, squawk) (dump1090prom_aircraft_flight_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detail information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Aircraft Track in Degree",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hex) (dump1090prom_aircraft_track_degrees)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Track Std Deviation",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hex) (dump1090prom_aircraft_track_degrees)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Heading in Degree",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hex) (dump1090prom_aircraft_nav_heading_degrees)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Heading Magnetic in Degree",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hex) (dump1090prom_aircraft_magnetic_heading_degrees)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Mach Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_mach_number",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Ground Speed in Knots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "sum by(hex, flight) (dump1090prom_aircraft_ground_speed_knots)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Bundespolizei",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_flight_info{squawk=\"0023\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rotational Speed (Degree/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "expr": "sum(dump1090prom_aircraft_track_rate_degrees_per_second) by (hex)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Indicated Air Speed in knots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_indicated_airspeed_knots",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Vertical Rate Feet per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_barometric_vertical_rate_feet_per_minute",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft RSSI dBm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "dump1090prom_aircraft_rssi_dbm", "legendFormat": "{{hex}}" }
   ]
  },
  {
   "title": "Aircraft Geom Height Feet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_altitude_geom_feet",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Flight Info",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum by(hex) (dump1090prom_aircraft_flight_info)",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Baro Height Feet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_altitude_baro_feet",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Mode A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    { "expr": "dump1090prom_aircraft_mode_a", "legendFormat": "{{hex}}" }
   ]
  },
  {
   "title": "Aircraft Seen Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dump1090prom_aircraft_seen_seconds",
     "legendFormat": "{{hex}}"
    }
   ]
  },
  {
   "title": "Aircraft Mode C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    { "expr": "dump1090prom_aircraft_mode_c", "legendFormat": "{{hex}}" }
   ]
  }
 ]
}