name: Dump1090Prom - Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Project Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22', '1.23', '1.24' , '1.25', '1.26' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Caching...
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-dump1090prom

      - name: Build Go Codebase
        run: make build
